version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: case
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: case
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend
    restart: always
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://user:123@mysql:3306/case"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]

volumes:
  mysql_data:
