# Usar a imagem oficial do Node.js como base
FROM node:18-alpine

# Definir o diretório de trabalho dentro do container
WORKDIR /app

# Copiar o package.json e o package-lock.json (ou yarn.lock) para o container
COPY package*.json ./

# Instalar as dependências
RUN npm install

# Copiar o restante do código para o container
COPY . .

# Expor a porta que o Fastify vai rodar
EXPOSE 3000

# Comando para rodar o servidor no modo de desenvolvimento
CMD ["npm", "run", "dev"]
